### ISSUE TITLE
Why Pose-NDF just use 21 joints?

### ISSUE THREAD

**Issue by HospitableHost** [garvita-tiwari/PoseNDF#9]
From the information in the released file ./config/amass.yaml and the code of function "get_parent_mapping", we know that the Pose-NDF just use 21 joints. But the SMPL Pose has 23 joints (without global orient). So which joints does Pose-NDF drop?
![image](https://user-images.githubusercontent.com/44576391/211260245-32f9f4f1-eb7d-4d0f-811f-42c56d8b1adb.png)

**Comment by garvita-tiwari** [comment]
Hi, We decided to exclude root joint(id 0) and wrist keypoints(id 22 and 23) from [SMPL joints](https://nextcloud.mpi-klsb.mpg.de/index.php/s/D4pTX2Cx62kQ9Wm). 

Root joint(global orientation) was excluded, because:
1. we are only modeling possible poses, irrespective of global orientation.
2. Including global orientation will make the learning difficult as the network might learn any wrong correlations between plausible poses and global orientation.

Wrist keypoints were excluded purely for our convenience of visualisaing/debugging code. As we are using smplx lib, which takes two separate input for poses -> body joint(21 keypoints) and hand joints(SMPL+H). We just ignored hand keypoints. 
If you want, you can train the network with 23 joints, by making following changes: 

1. Edit the smpl_mappings in model/network/net_utils.py with following:

smpl_mappings = [ -1, -1, -1, 1,2,3,4,5,6,7,8,9,9,9,12,13,14,16,17,18,19,20, 22]

2.  Prepare data from scratch and modify line 48 in data/sample_poses.py.  Specifically, replace pose_body.extend(fullpose[:, 3:66]) with pose_body.extend(fullpose[:, 3:72]).


I hope this helps.


> From the information in the released file ./config/amass.yaml and the code of function "get_parent_mapping", we know that the Pose-NDF just use 21 joints. But the SMPL Pose has 23 joints (without global orient). So which joints does Pose-NDF drop? ![image](https://user-images.githubusercontent.com/44576391/211260245-32f9f4f1-eb7d-4d0f-811f-42c56d8b1adb.png)
